name: Merging into Master Branch
on:
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js 14.x
                uses: actions/setup-node@v2-beta
                with:
                    node-version: '14'
            -   name: Cache node modules
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.npm
                        ~/cache
                        !~/cache/exclude
                        **/node_modules
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-
            -   name: Install Dependencies
                run: npm ci
            -   name: Build Repo
                run: npm run build -- --prod
